### ISSUE TITLE
dev's dead?

### ISSUE THREAD

**Issue by NicolasPL64** [m4heshd/whatsapp-desktop-dark#106]
dev's dead?
bruh moment

**Comment by omar-shukurov** [comment]
yeaa

**Comment by RuggeDX** [comment]
No idea what happened either, he just disappeared...

**Comment by vednoc** [comment]
The upstream project is very much alive. Read more in #97. :smiley:

**Comment by NicolasPL64** [comment]
> The upstream project is very much alive. Read more in #97. 😃

Yeah but your version is for web WA, and I use Desktop WA.

**Comment by vednoc** [comment]
> Yeah but your version is for web WA, and I use Desktop WA.

I don't know the difference between desktop and web version these days, but what I remember from using it a couple of years ago it was more or less the same thing.

I commented mainly because people here aren't familiar with another way to get dark mode on WA.

**Comment by m4heshd** [comment]
@vednoc No, your stylesheet is not the upstream of my complex JS injector. Everyone's welcome to read https://github.com/m4heshd/whatsapp-desktop-dark/issues/97#issuecomment-565853183 for a proper explanation. 

### **And to all supporting users who are concerned, please keep in touch because this and me "the developer" are very much alive. An update will be out soon.**
