### ISSUE TITLE
2 Vulnerabilities while installing?

### ISSUE THREAD

**Issue by VivekSharma1897** [m4heshd/whatsapp-desktop-dark#12]
[https://imgur.com/a/oDVAEU4](url) 1 is moderate while other is high

**Comment by m4heshd** [comment]
Hi @VivekSharma1897,
You can simply ignore these warnings because these are originated from one specific module called  [resourcehacker ](https://www.npmjs.com/package/resourcehacker) which is not essential to the functionality of this script. This module is used to apply the icon to windows binary output which you can see here in this commit - 5d3bec963eff3841454b91938d8e0aa91ebace9a

If this continues to exist, i might get rid of the module in a future update. I'll wait a while till the developer of this module address the issue.
