### ISSUE TITLE
Just cosmetic, would you change the icon of the application?

### ISSUE THREAD

**Issue by joaoavilars** [m4heshd/whatsapp-desktop-dark#15]
Could you include in the script to change the icon too?
This blue was good, but personally I put black ...

![image](https://user-images.githubusercontent.com/42388872/64351192-420ff500-cfd0-11e9-9861-ed244acee87a.png)

**Comment by m4heshd** [comment]
I'm sorry but doing this would complicate the process a bit and the script would most likely be detected as a malware for that behavior. 
But i can put you on the right path since the script already have the capability of achieving what you're asking. Take a look at this commit 5d3bec963eff3841454b91938d8e0aa91ebace9a. All you have to do is take the executable path from the variable `WAPath` set after this line https://github.com/m4heshd/whatsapp-desktop-dark/blob/5830901483d66df5fcf07a85b2b30047418eed4b/run-win32.js#L44 and apply the icon to that file using the same method mentioned above. Here's the function you can use:

```
function setWAIcon(exePath) {
    let command = ' -open "' + exePath + '" ' +
        '-save "' + exePath + '" ' +
        '-action addoverwrite ' +
        '-res "' + path.join(__dirname, 'icons', 'NEW_DARK_ICON.ico') + '" ' +
        '-mask ICONGROUP,1,1033 ' +
        '-log NUL';

    exec(path.join('node_modules', 'resourcehacker', 'bin', 'ResourceHacker.exe') + command, function (error) {
        if (error) {
            console.log(error);
            console.log('\x1b[31m%s\x1b[0m', 'Failed to set the dark WhatsApp icon.\n');
        }
    });
}
```

You can add that task somewhere inside the `applyDarkStyles()` function in [run-win32.js](https://github.com/m4heshd/whatsapp-desktop-dark/blob/master/run-win32.js) as `setWAIcon(WAPath);` since the variable `WAPath` will be set by then. Good luck and lemme know how it goes. 🙂

**Comment by OBadstue** [comment]
@joaoavilars Would you mind sharing where you got the icon? I've been looking for a black/dark one but couldn't find one i liked. (sorry if this is the wrong place to post this)

**Comment by joaoavilars** [comment]
@OBadstue no problem!! 👍 
well i searched for a PNG icon image and found this one:
https://images.app.goo.gl/bkG6jKvBEUWyoupz7
I then used https://convertio.co/en/png-ico/ to do the conversion

**Comment by joaoavilars** [comment]
only I'll try others, because this Windows left with a dubious quality.

![image](https://user-images.githubusercontent.com/42388872/65246369-ced4ab80-dac4-11e9-9942-eedb2bb08e5b.png)
