### ISSUE TITLE
Add blocked contact grey and Stickers menu arrow white

### ISSUE THREAD

**Issue by timea-techgirl** [m4heshd/whatsapp-desktop-dark#22]
1) How to make it darker?

2) Stickers menu arrow is white.

![Wa](https://user-images.githubusercontent.com/7058205/64549915-614faf00-d34f-11e9-8cb3-ea3b964565ec.jpg)

**Comment by m4heshd** [comment]
Hi @timeakesmarky,
Both of these issues will be fixed in the next release. Thanks for reporting.

**Comment by timea-techgirl** [comment]
@ m4heshd Another bug:
When I try to add a profile picture, the + and - zoom buttons are white.

**Comment by m4heshd** [comment]
Noted. The bottom part also seems to be light colored on the modal. Thanks for reporting.

**Comment by m4heshd** [comment]
Hi @timeakesmarky,
The issues you raised were fixed in a139ff1a068ece4143ded6c2ef532dd4e61fc739 & fb0acc1776bd7b1308f8753f69b0dd01ccc8a45c. Unfortunately issue no.1 from the screenshot will remain as it is since it was actually meant to look that way and it shares a huge set of common style classes which will break almost the entire left pane. Closing this since everything else has been fixed.
