### ISSUE TITLE
Error number -4058 (Special character in directory structure)

### ISSUE THREAD

**Issue by ghost** [m4heshd/whatsapp-desktop-dark#29]
I can´t install WhatsApp Darkmode on Desktop!
I think because the invalid characters like ä ö ü etc. 

The file exists in C:\Users\Sören\AppData\Local\WhatsApp\app-0.3.4479\resources\app.asar

![image](https://user-images.githubusercontent.com/33805688/65331900-ea6fad00-dbbd-11e9-831e-47137a5b7049.png)

**Comment by m4heshd** [comment]
Hi @CrashedLife,
Just as i suspected and also as you mentioned, It's the diacritic letter "**ö**" in your username "**Sören**". I ran a test. Take a look. 

![image](https://user-images.githubusercontent.com/6711514/65334194-8c53c180-dbdf-11e9-9ecc-6d27e080a96d.png)

WMIC returns the correct string but somewhere inside the `ps-node` module, this string loses its properties. Unfortunately It's not possible to fix this on the release since it rises from a dependency but you can apply a workaround by editing the source. You need to set the following line

https://github.com/m4heshd/whatsapp-desktop-dark/blob/81a3f8763c1a64aac23a7b7440d08f283b64d5d9/run-win32.js#L45

To `WAPath = 'C:\Users\Sören\AppData\Local\WhatsApp\app-0.3.4479\WhatsApp.exe';` and run the script directly from source. Instructions are in the [documentation](https://github.com/m4heshd/whatsapp-desktop-dark#build-the-installation-script-yourself). Good luck.. 🙂

**Comment by ghost** [comment]
Hey, first of all thank you for your fast reply!
I´ve build the source manually but i got now a new error.
They can´t find the resources and the path is now "C:\resources\app.asar".

![image](https://user-images.githubusercontent.com/33805688/65371997-46900b00-dc6a-11e9-8ed5-2654375a3b3f.png)


I hope you can help me soon,
Sincely Sören.

**Comment by m4heshd** [comment]
That's really weird. Did you edit the variable exactly as i mentioned?

**Comment by revi97** [comment]
Why dont you try installing WhatApp desktop and run PowerShell in the folder and enter **node .**  . But make sure node is installed globally or else sometimes it won't work. One of my friend had same problem and fixed it by doing as I mentioned and it worked without a problem. And make sure it is not in the user folder and place the downloaded folder in a drive and then run from there. It should work. 


![Capture](https://user-images.githubusercontent.com/9878771/65594074-a3aff780-dfaf-11e9-9f5d-de16ea9b5960.PNG)

**Comment by ghost** [comment]
I´ve been fixed now.

I´m copied the "whatsapp-desktop-dark" to my C:\ drive but It didn´t found the app.asar
Then I´m created in the C:\ Drive an folder called "resources" and copied the app.asar in it and run the Darkmode Setup.

It´s found and injected this style and I´m pasted the app.asar in the old whatsapp folder and now its worked :)

Thank you @m4heshd & @revi97 for your support.

Have a nice day.

![image](https://user-images.githubusercontent.com/33805688/65831712-55f00380-e2bd-11e9-9640-3a1f7992382c.png)

![image](https://user-images.githubusercontent.com/33805688/65831813-b1ba8c80-e2bd-11e9-87c2-2afe370388a8.png)


===================== CLOSED =============================

**Comment by m4heshd** [comment]
Glad you managed to get it to work. But i still find it bizarre that that even after setting a static path to the variable, application still managing to snoop around some other random path.

**Comment by revi97** [comment]
@CrashedLife  Copying it in C drive won't allow as it requires admin permissions hence it might have not worked at that time. 
AND
@m4heshd even I don't know why it happens but this usually fixes things.

**Comment by ghost** [comment]
@m4heshd Same I did´nt understand why this not worked. 

@revi97 I´ve everytime admin permissions for my C:\ drive but it works for me only on this way i think.
The setup can´t replace the old file too cuz they didn´t use the backslash character.
It´s weird but it´s worked now.

Thanks for your support :)

**Comment by m4heshd** [comment]
@revi97 Actually It'll work fine inside the drive **C:** as it already worked for him since the drive itself isn't protected by elevated write privileges. It's just some directories such as `Program Files`, `Windows`..etc. Even the local app data directory has write permissions set to everyone. That's why most of the applications that constantly change its resources are installed in app data directory including Electron builds. 

Simply changing the global variable that i used everywhere inside the script to identify location should do the task without hesitation. If @CrashedLife edited the source correctly, there shouldn't be a single complication. Else the issue has a deeper explanation way beyond what i can see from here.

**Comment by nickmz98** [comment]
hey guys, couldn't get it work, I had the same problems as @CrashedLife and I was following the same steps as mentioned, got to the part of creating the new folders in C drive and running the .exe file but then I got a new issue, I don't know if I f- it up somewhere in the process or if I should try another way. Not a programmer, only a geek for dark mode, would really appreciate any help, thanks in advance.
![new problem](https://user-images.githubusercontent.com/56243014/66890891-36d7be00-efad-11e9-95fa-94b2f4a41be8.png)

**Comment by m4heshd** [comment]
Hi @nickmz98, There's a directory named `app.asar.unpacked` right next to the `app.asar` in WhatsApp resources directory. You need to keep those together for the extraction to work properly.

**Comment by nickmz98** [comment]
Hey @m4heshd, followed the instructions, seems to be working just fine up until the "Cleaning up" stage, where the WADark.exe suddenly closes and the mod is not applied, for the looks of it, it seems I´m most of the way there, just having this problem.

**Comment by m4heshd** [comment]
@nickmz98, try running `WADark.exe` from powershell where it won't close automatically so we can see the error.

**Comment by nickmz98** [comment]
Hey @m4heshd, ran it in Power Shell, and this was what I got.
![running_power_shell](https://user-images.githubusercontent.com/56243014/66929880-62809580-eff9-11e9-8842-ef457b7a7994.png)
