### ISSUE TITLE
why no linux :(

### ISSUE THREAD

**Issue by syntaxhacker** [m4heshd/whatsapp-desktop-dark#4]
can we get a linux version?

**Comment by m4heshd** [comment]
Hi @syntaxhacker,

I couldn't do a Linux release because there's no official WhatsApp desktop build for Linux. I've seen some unofficial clients but It's a bit of hassle to keep track of two types of clients for updates. Thanks for raising this question because I'm guessing a lot of people must be wondering about this.

**Comment by DanielRios549** [comment]
I use WhatsApp Desktop from Linux Mint repository, it works out of the box, and there is an option to add a custom CSS file, I downloaded one from userstyles.org website and add it to the program, you can download the .deb file in the following link.

http://packages.linuxmint.com/pool/import/w/whatsapp-desktop/whatsapp-desktop_0.6.1_amd64.deb

**Comment by m4heshd** [comment]
I think the above mentioned program loads the vanilla `web.whatsapp.com` page into a chromium windows. That's why the styles from userstyles.org work on the program. But either way anything that'll work for you is great.

I was thinking of recompiling the official WhatsApp desktop version for Linux but that's a project for another time because there's gonna be so many complications.

**Comment by DanielRios549** [comment]
Either the official version loads `web.whatsapp.com` in a chromium window, there is no native version of WhatsApp Destkop for PC, the problem is that the official version there is no option to add a custom CSS file, what this program does is just modify the default CSS file instead of load another one to rewrite the styles.

**Comment by syntaxhacker** [comment]
Ok thanks @DanielRios549

**Comment by m4heshd** [comment]
@DanielRios549 official version works with the API. It doesn't load the webpage into a browserwindow. You can check that in the source.

**Comment by DanielRios549** [comment]
@m4heshd I didn't know that, I even didn't know WhatsApp had an API, thanks

**Comment by m4heshd** [comment]
No worries. Glad to be helpful. I'll keep this issue open and pinned so everybody can get an understanding about the lack of a Linux version.

**Comment by mBEDed** [comment]
can we have anything as browser extension? It would be a great help. Thanks, man. Happy Coding.

**Comment by vednoc** [comment]
> can we have anything as browser extension? It would be a great help. Thanks, man. Happy Coding.

The project @m4heshd's work relies on was made to work with browser extension(s), check out [vednoc/dark-whatsapp](https://github.com/vednoc/dark-whatsapp) for more info.

**Comment by m4heshd** [comment]
@vednoc No, my project doesn't rely on your anything. Stop doing false statements. And please stop spamming on every thread. Everyone's welcome to read https://github.com/m4heshd/whatsapp-desktop-dark/issues/97#issuecomment-565853183 for a proper explanation.
