### ISSUE TITLE
Color roll back fix for updated WhatsApp

### ISSUE THREAD

**Issue by revi97** [m4heshd/whatsapp-desktop-dark#40]
- So the WhatsApp desktop app goes back to original color if you update it. 
- I tried a bunch of methods and came up with this and it's working properly.
- But it can be fixed by changing the version in [here](https://github.com/m4heshd/whatsapp-desktop-dark/blob/master/package.json) in the repository.

**Comment by m4heshd** [comment]
Hi @revi97, 
I'm sorry but i can't seem to understand you properly. Version increment in dark mode `package.json` is done according to each release. There's no way to stop it from going back to the light theme because Squirrel package manager used by WhatsApp creates a completely new directory structure upon each update. 

![image](https://user-images.githubusercontent.com/6711514/65600107-1a9fbd00-dfbd-11e9-8bac-34cf8b674cca.png)

The versioning in this repo technically has nothing to do with the WhatsApp versioning itself. I use the same versioning as WhatsApp just to avoid any confusion and roll out dark mode updates properly with each release. That's the same reason why i use the version from `package.json` inside this repo to check for new dark mode updates. You can take a look at the functionality here in [this commit](https://github.com/m4heshd/whatsapp-desktop-dark/commit/af12c5477eb562861402db653068562b3d241a96). 

Hope i cleared it up.

**Comment by revi97** [comment]
I am sorry. But I don't know what happened, after WhatsApp desktop updated, the dark mode was no where to be found and hence tried to change version number in package.json and it's been working properly from that time. So thought it was like that for others too

**Comment by m4heshd** [comment]
> the dark mode was no where to be found

Do you mean the script files or the theme itself? 

If you were referring to the theme, it should revert back to the original theme upon a WhatsApp update and it's indeed how it's suppose to work. It's already been mentioned in the documentation [right here](https://github.com/m4heshd/whatsapp-desktop-dark#my-whatsapp-turned-back-to-light-theme-after-sometime-what-to-do). There's nothing we could do about that. I still don't understand what was going on with the version number.
