### ISSUE TITLE
Add a separate color for seen and send messages

### ISSUE THREAD

**Issue by revi97** [m4heshd/whatsapp-desktop-dark#41]
While we need to change the looks of the desktop app we need to alter the accent but by default, it also alters the **seen and send** color, it would be great if you could add another color and set that to **send and seen** option in CSS.

**Comment by m4heshd** [comment]
I'm guessing you're meaning the "blue ticks" for read status. There were some other conversations about this in #36 and https://github.com/m4heshd/whatsapp-desktop-dark/issues/5#issuecomment-534396690. We either have to keep the ticks permanently blue or keep it the way it is. 

I personally think the ticks should match accent color but it does get confusing if the accent color is similar to the color of "delivered" ticks as mentioned in https://github.com/m4heshd/whatsapp-desktop-dark/issues/36#issuecomment-534634866. I'll definitely take this into consideration in next release.

**Comment by revi97** [comment]
Yea. The blue ticks. I think it'll work if u keep make a separate color and then use it for blue tick instead of accent color. It will work, as I have tried it out and it's working for me. It may sound weird to do so, but it will surely work. In the css file, there is comment as **send and seen* change color there and check.

**Comment by m4heshd** [comment]
I know i can simply isolate the element and set a static color but the thing is then a lot of people might get the need to customize the color of blue ticks. That means an extra step for the installation process which complicates things. Not everybody's comfortable editing CSS. Most of the users are regular ones with beginner level knowledge on all these things. So i have to think inside everyone's shoes.

> there is comment as *send and seen change color there and check

Yes there is. The terms and structures we use change over the time and i hardly remember ones i wrote months back. If you look closely there might be a ton of redundant styles which i updated over the time because these were written to override styles generated through frameworks dynamically. So yeah. It's CSS which is very loosely written and hard to clean up. 🙂

**Comment by revi97** [comment]
That's true. Will search through and remove them if they are not useful. Thanks for faster responses
