### ISSUE TITLE
Name of someone that haven't saved in contacts it black on black

### ISSUE THREAD

**Issue by Idomo** [m4heshd/whatsapp-desktop-dark#66]
Hi,
When someone isn't saved into your contacts (for example, in a big group), it shows their name next to their number (the one they’ve chosen in settings).
The issue is that this name is black, while the background of the message bubble is in the same color, so I have to mark the name with the cursor to be able to see it.

Example:
![image](https://user-images.githubusercontent.com/26777129/66316854-11014800-e921-11e9-9a77-06268fdfb2eb.png)

**Comment by m4heshd** [comment]
Hi @Idomo,
That's odd because It's fine on ours. You sure you're on the latest version? If you are, then this might be specific to your RTL design because i remember specifically fixing that particular element.

![image](https://user-images.githubusercontent.com/6711514/66319457-c8ef1f00-e93a-11e9-882d-d51ad7a7b94a.png)

**Comment by Idomo** [comment]
I've updated today, so yes, I'm sure.
May you check on your side with RTL?

**Comment by m4heshd** [comment]
Unfortunately I can't change the language at the moment because it might make a lot of things difficult for me. Maybe we'll try on the Telegram group. Maybe you can join the conversation and give it a little push. https://t.me/wadarkmodechat

Also can you confirm WhatsApp version and Dark mode version?

**Comment by Idomo** [comment]
Just for the record (we've talked about this in the Telegram group):
Both WhatsApp and WADark versions are `0.3.4941`.

**Comment by m4heshd** [comment]
Closing this since it has been moved to #124
