### ISSUE TITLE
Installation on Mac OS?

### ISSUE THREAD

**Issue by sjwdavies** [m4heshd/whatsapp-desktop-dark#79]
What am I missing here, how do I actually install it?

**Comment by HillTravis** [comment]
Download the .zip file [here](https://github.com/m4heshd/whatsapp-desktop-dark/releases/download/0.3.4941/WADark-0.3.4941-macOS.zip), it should get unzipped automatically, then look for the folder in your Downloads folder called **WADark-mac**, inside should be a file called WADark. You need to run this file.

For me, there were a few extra steps not mentioned in the instructions. In order to run the file, open your Terminal, then run `cd ~/Downloads/WADark-mac && chmod a+x WADark && ./WADark`. You may also need to allow it through your security settings (first try to run it and if it gets blocked, go to the Apple menu > System Preferences > Security & Privacy > Open Anyway).
