### ISSUE TITLE
Include the original license from vednoc/dark-whatsapp

### ISSUE THREAD

**Issue by vednoc** [m4heshd/whatsapp-desktop-dark#97]
Hi,

I would appreciate if you included the license from [vednoc/onyx] as per conditions of the MIT license. Also, it would be cool if you linked to my project in the readme so people can find another way to use dark theme much more easily, as well as users on Linux that don't have an official WA Desktop app.

Considering there are people that don't know about my project (your project got slightly over twice the amount of stars in far shorter amount of time) and/or don't know how to get dark theme on WhatsApp that runs in all major browsers without having to deal with installing Nodejs/Electron/NPM on their computers, it would be a fairly appropriate thing to do.

Thank you in advance.

[vednoc/onyx]: https://github.com/vednoc/onyx

**Comment by linuxct** [comment]
+1 to this, although this project seems dead.

**Comment by vednoc** [comment]
Seems like it. Anyways, I've changed the name of my repository, so now it goes by [vednoc/dark-whatsapp](https://github.com/vednoc/dark-whatsapp).

**Comment by NicolasPL64** [comment]
Nice!!

**Comment by NicolasPL64** [comment]
Nice!! But I use the desktop version, not the web one :/

**Comment by m4heshd** [comment]
Hi @vednoc,

I have to say that i mean no offence by any of this. Your hard work is really appreciated.

1. First of all, your project and my project, completely different things. The attraction of my project is not a stylesheet but the amount of hard work that went into reverse-engineering and reading source files with hundreds of thousands of code lines just to get a proper debug process running. It wasn't as easy has hitting "F12" on a browser or doing "Inspect Element". Only i know how hard i've worked to get the script running. The actual attraction of the project is the Injection itself. Even the day to day user that's here is changing and doing all new things with the stylesheet and that's my least priority. Go through my project to get a better understanding. So are free to stop referring your project as the "Upstream" of this project and my project being "relying" on your project. 

2. Stylesheet - I admit that when i got into this first i tried to go by the lazy way and take shot at your stylesheet just because i liked your color palette which i mentioned in d991f4172cb1516e739b04d92dba517afe141b46. But as soon i started actually doing the debugging i realized what a stupid mistake it was. They were completely different styling and elements. But i was too deep into it and it was too late to clean the previous commits and start over. Only thing came out of it was wasting a ton of my time which i could've cut in more than a half if i wrote the styles from the scratch. And the best part is, i ended up doing that. FYI do a diff of the first version of your stylesheet and the current version of mine. Completely rewritten. More than 86% replaced. And the remaining parts are just general CSS syntax which you don't own. So again.. Completely different projects.

3. Who told you that people need to install Nodejs/Electron/NPM on their devices just to have my script running? Please read the documentation and get your facts straight first. People don't need to do anything but download an executable and simply run it. It's not my responsibility if WhatsApp itself rely on those dependencies.

4. I've added your license information on 28d0763d9a87388e67296345d905e6ce650fc97e just because of my stupid mistake in d991f4172cb1516e739b04d92dba517afe141b46 made me legally obliged to do so. That's all that's gonna happen.

5. I don't need randoms walking by here to give my project death certificates when there are actual people working really hard to keep this alive on our Telegram and XDA. Sometimes people just stumble into hard situations in life and cannot spare time to anything else. All the death declarations will be deleted by me personally since this is very much alive.

6. You need to understand this. Every single user here is aware about the failure of a product that's called "WhatsApp Web" and everybody knows about DarkReader and Stylish/Stylus userscript themes. But people hate WhatsApp web. Why would somebody want to run their most personal encryption supported messenger on a tracker ridden heavy web browser when they can simply user an isolated, much more platform level supported desktop application? It's has turned into something people use on emergencies. I've personally hated it myself and will never ever use it just like the majority here. So to address your issue with the number of **"Stars"**, it's not my fault that people are attracted to the more practical way of using WhatsApp on a desktop. Analytics speak for themselves. I've seen that your project is promoted much much more than my project in online media but if people still reject it there's a fair reason. **So kindly STOP HAUNTING MY PROJECT REPLYING TO EVERY SINGLE THREAD BASHING MY HARD WORK TRYING TO PROMOTE USELESS WHATSAPP WEB**.

Again sorry about the rant but this needed to be said. Closing this.
